spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?user=postgres.bymfeiisrlfplkhhkfdt&password=Lcgps8ArupS4w6Mv
spring.datasource.username=postgres.bymfeiisrlfplkhhkfdt
spring.datasource.password=Lcgps8ArupS4w6Mv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080