spring.datasource.url=jdbc:postgresql://db.bymfeiisrlfplkhhkfdt.supabase.co:5432/postgres?user=postgres&password=Lcgps8ArupS4w6Mv
spring.datasource.username=postgres
spring.datasource.password=Lcgps8ArupS4w6Mv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true